version: '3.8'
services:
  app_blue:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - COLOR=blue
    command: >
      uvicorn app.asgi:application
      --host 0.0.0.0 --port 8000
      --workers 2
      --loop uvloop
    networks:
      - web

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
    networks:
      - web
  
  app_green:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - COLOR=green
    command: >
      uvicorn app.asgi:application
      --host 0.0.0.0 --port 8000
      --workers 2
      --loop uvloop
    networks:
      - web

networks:
  web:
    driver: bridge