version: '3.8'
services:
  app_blue:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - COLOR=blue
    networks:
      - web

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
    networks:
      - web
  
  app_green:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - COLOR=green
    networks:
      - web

networks:
  web:
    driver: bridge